#!/usr/bin/env bash
########################################################################
# gen-i0varfst-shim.sh  —  generate a JS shim that defines the 6
# [i0varfst_*] functional-set helpers that are REFERENCED but NEVER
# DEFINED in the prebuilt frontend/BUILD/lib2xats2cc.js.
#
# WHY THIS EXISTS (xats2go M1):
#   The prebuilt lib2xats2cc.js (intrep0 + trxd3i0) emits calls to
#   i0varfst_mknil / i0varfst_mklst / i0varfst_addvar / i0varfst_addlst
#   / i0varfst_listize / i0varfst_strmize when [trxd3i0] computes the
#   free-variable set of ANY function declaration. But the funset/funmap
#   (avltree-backed) library those impls depend on failed template
#   resolution at the time lib2xats2cc.js was built, so the impls landed
#   inside a commented-out  // I1Dnone1(...)  errck blob while the call
#   sites survived. Result: `ReferenceError: i0varfst_mklst_NNNNN is not
#   defined` for any program containing a function (incl. the prelude).
#   test00 (val theAnswer=42) never hit this; test01 (a real print) does.
#
#   This is a PRE-EXISTING frontend-bundling defect, independent of the
#   Go emitter. Rebuilding lib2xatsopt.js (171MB) is forbidden, and
#   rebuilding lib2xats2cc.js is out of scope for M1, so we surgically
#   supply the 6 missing impls as a small, semantically-faithful JS shim
#   that is prepended to the emitter bundle.
#
# SEMANTICS (mirrors srcgen2/xats2cc/srcgen1/DATS/intrep0_utils0.dats):
#   i0varfst = a functional SET of i0var, KEYED + ORDERED by the var's
#   stamp (an int): key(v) = stamp_get_uint(d2var_get_stmp(i0var_dvar$get(v))).
#   We represent the set as a JS array sorted ascending by key, deduped.
#   - mknil()         -> []
#   - addvar(s,v)     -> insert v (dedup by key, keep sorted)
#   - mklst(vs)       -> fold list of i0var through addvar
#   - addlst(s,vs)    -> fold list of i0var through addvar
#   - listize(s)      -> a JS list_vt(i0var):  nil=[0], cons=[1,h,t]
#   - strmize(s)      -> a real lazy strm_vt(i0var) so the inlined
#                        strm_vt_listize0 in trxd3i0_decl00 can walk it,
#                        built from XATS2JS_lazy_vt_make_f0un +
#                        XATS2JS_strmcon_vt_{cons,nil}.
#
# Stamps differ per lib2xats2cc build, so we DISCOVER the exact stamped
# names from the bundle at generation time (robust to rebuilds).
#
# Usage:  gen-i0varfst-shim.sh  <linked-bundle.js>  <out-shim.js>
########################################################################
set -uo pipefail
BUNDLE="$1"; OUT="$2"

# resolve a stamped name `name_NNN(` referenced in the bundle (first hit)
ref() { grep -m1 -oE "$1"'_[0-9]+' "$BUNDLE"; }

MKNIL=$(ref 'i0varfst_mknil')
MKLST=$(ref 'i0varfst_mklst')
ADDVAR=$(ref 'i0varfst_addvar')
ADDLST=$(ref 'i0varfst_addlst')
LISTIZE=$(ref 'i0varfst_listize')
STRMIZE=$(ref 'i0varfst_strmize')

# defined helpers we call into (these ARE defined in the bundle)
I0VAR_DVAR=$(grep -m1 -oE 'i0var_dvar\$get_[0-9]+' "$BUNDLE")
D2VAR_STMP=$(grep -m1 -oE 'd2var_get_stmp_[0-9]+' "$BUNDLE")
STMP_UINT=$(grep -m1 -oE 'stamp_get_uint_[0-9]+' "$BUNDLE")

missing=0
for v in MKNIL MKLST ADDVAR ADDLST LISTIZE STRMIZE I0VAR_DVAR D2VAR_STMP STMP_UINT; do
  if [ -z "${!v}" ]; then echo "!! gen-shim: could not resolve $v in $BUNDLE" >&2; missing=1; fi
done
[ "$missing" -eq 0 ] || exit 1

# --- SECOND DEFECT (xats2go M2.1): tokenfpr missing in lib2xats2js.js -------
# The prebuilt JS-backend reference lib2xats2js.js REFERENCES but never
# DEFINES `tokenfpr` (the token pretty-printer), so js1emit crashes with
# `ReferenceError: tokenfpr_NNNN is not defined` the moment it emits an
# I1INSlam0 / I1INSfix0 (a lambda / fixpoint) -- which the arithmetic /
# print TEMPLATES instantiate. This blocks the differential-vs-JS ORACLE
# for any program with primops. Same pre-existing-bundling-defect class as
# i0varfst (the Go emitter is unaffected; this only restores the JS oracle).
# tokenfpr is called ONLY inside a `// comment` in the emitted JS (`// lam0(
# <tok>)`), so its output never affects the JS program's runtime stdout; a
# faithful no-op that prints nothing is byte-safe for the oracle. We define
# it only if the bundle actually references it (the Go bundle does not).
TOKENFPR=$(grep -m1 -oE 'tokenfpr_[0-9]+' "$BUNDLE")

cat > "$OUT" <<EOF
//==XATS2GO-JSSHIM-BEGIN== (generated by gen-i0varfst-shim.sh)
// Supplies the 6 i0varfst_* funset helpers missing from lib2xats2cc.js,
// and (for the JS-backend reference) the missing tokenfpr.
// See gen-i0varfst-shim.sh for the full rationale.
//
// key(v): order/dedup an i0var by its stamp (an int).
function XATS2GO_i0varfst_key (v) {
  return ${STMP_UINT}(${D2VAR_STMP}(${I0VAR_DVAR}(v)));
}
// insert v into sorted-deduped array s (returns a NEW array).
function XATS2GO_i0varfst_ins (s, v) {
  var k = XATS2GO_i0varfst_key(v);
  var r = []; var i = 0; var n = s.length;
  while (i < n && XATS2GO_i0varfst_key(s[i]) < k) { r.push(s[i]); i++; }
  if (i < n && XATS2GO_i0varfst_key(s[i]) === k) { return s; } // already present
  r.push(v);
  while (i < n) { r.push(s[i]); i++; }
  return r;
}
let ${MKNIL} = function () { return []; };
let ${ADDVAR} = function (s, v) { return XATS2GO_i0varfst_ins(s, v); };
// fold a JS list (nil=[0], cons=[1,h,t]) of i0var through addvar.
let ${MKLST} = function (vs) {
  var s = []; var p = vs;
  while (p[0] === 1) { s = XATS2GO_i0varfst_ins(s, p[1]); p = p[2]; }
  return s;
};
let ${ADDLST} = function (s, vs) {
  var p = vs;
  while (p[0] === 1) { s = XATS2GO_i0varfst_ins(s, p[1]); p = p[2]; }
  return s;
};
// array -> JS list_vt(i0var):  nil=[0], cons=[1,h,t]
let ${LISTIZE} = function (s) {
  var r = [0];
  for (var i = s.length - 1; i >= 0; i--) { r = [1, s[i], r]; }
  return r;
};
// array -> lazy strm_vt(i0var) that strm_vt_listize0 can walk.
let ${STRMIZE} = function (s) {
  function mk (i) {
    return XATS2JS_lazy_vt_make_f0un(function () {
      if (i >= s.length) { return XATS2JS_strmcon_vt_nil(); }
      return XATS2JS_strmcon_vt_cons(s[i], mk(i + 1));
    });
  }
  return mk(0);
};
// Backend-owned helper used by go1emit_utils0.dats when emitting evaluated
// char literals. It returns the body of a Go rune literal, without quotes.
function XATS2GO_gochar_esc(c0) {
  switch (c0) {
    case 10: return "\\\\n";
    case 9: return "\\\\t";
    case 13: return "\\\\r";
    case 8: return "\\\\b";
    case 12: return "\\\\f";
    case 11: return "\\\\v";
    case 39: return "\\\\'";
    case 92: return "\\\\\\\\";
  }
  if (c0 >= 32 && c0 !== 127) { return String.fromCharCode(c0); }
  if (c0 <= 0xff) { return "\\\\x" + c0.toString(16).padStart(2, "0"); }
  if (c0 <= 0xffff) { return "\\\\u" + c0.toString(16).padStart(4, "0"); }
  return "\\\\U" + c0.toString(16).padStart(8, "0");
}
// Backend-owned adapter for raw FILR char output. The ATS-facing order is
// (filr, char); the JS node primitive is (char, filr).
function XATS2GO_chrfpr(filr, c0) {
  return XATS2JS_NODE_char_fprint(c0, filr);
}
//==XATS2GO-JSSHIM-END==
EOF

# tokenfpr: defined ONLY for the JS-reference bundle (the Go bundle has no
# such symbol). A faithful no-op -- it writes into a JS comment only -- so
# returning nil (the unit) without printing is byte-safe for the oracle.
if [ -n "$TOKENFPR" ]; then
  cat >> "$OUT" <<EOF
//==XATS2GO-JSSHIM-TOKENFPR-BEGIN==
let ${TOKENFPR} = function (filr, tok) { return [/*XATSNIL*/]; };
//==XATS2GO-JSSHIM-TOKENFPR-END==
EOF
fi

echo "   -> $OUT (i0varfst: mknil=$MKNIL mklst=$MKLST addvar=$ADDVAR listize=$LISTIZE strmize=$STRMIZE; tokenfpr=${TOKENFPR:-<none>})"
