(***********************************************************************)
(*                                                                     *)
(*                         Applied Type System                         *)
(*                                                                     *)
(***********************************************************************)

(*
** ATS/Xanadu - Unleashing the Potential of Types!
** Copyright (C) 2022 Hongwei Xi, ATS Trustful Software, Inc.
** All rights reserved
**
** ATS is free software;  you can  redistribute it and/or modify it under
** the terms of  the GNU GENERAL PUBLIC LICENSE (GPL) as published by the
** Free Software Foundation; either version 3, or (at  your  option)  any
** later version.
** 
** ATS is distributed in the hope that it will be useful, but WITHOUT ANY
** WARRANTY; without  even  the  implied  warranty  of MERCHANTABILITY or
** FITNESS FOR A PARTICULAR PURPOSE.  See the  GNU General Public License
** for more details.
** 
** You  should  have  received  a  copy of the GNU General Public License
** along  with  ATS;  see the  file COPYING.  If not, please write to the
** Free Software Foundation,  51 Franklin Street, Fifth Floor, Boston, MA
** 02110-1301, USA.
*)

(* ****** ****** *)
//
(*
Author: Hongwei Xi
(*
Sun Jul 24 18:09:47 EDT 2022
*)
Authoremail: gmhwxiATgmailDOTcom
*)
//
(* ****** ****** *)
(* ****** ****** *)
#define
ATS_PACKNAME
"ATS3.XANADU.xatsopt-20220500"
(* ****** ****** *)
(* ****** ****** *)
//
#include
"./../HATS/xatsopt_sats.hats"
#include
"./../HATS/xatsopt_dpre.hats"
//
(* ****** ****** *)
(* ****** ****** *)
#staload
_(*?*) = "./lexing0_print0.dats"
(* ****** ****** *)
#staload "./../SATS/lexing0.sats"
(* ****** ****** *)
#staload "./../SATS/staexp0.sats"
#staload "./../SATS/dynexp0.sats"
(* ****** ****** *)
#staload "./../SATS/staexp1.sats"
#staload "./../SATS/dynexp1.sats"
(* ****** ****** *)
#symload lctn with d1pat_get_lctn
#symload node with d1pat_get_node
(* ****** ****** *)
#symload lctn with d1exp_get_lctn
#symload node with d1exp_get_node
(* ****** ****** *)
#symload lctn with d1ecl_get_lctn
#symload node with d1ecl_get_node
(* ****** ****** *)
#symload lctn with q1arg_get_lctn
#symload node with q1arg_get_node
(* ****** ****** *)
#symload lctn with s1qag_get_lctn
#symload node with s1qag_get_node
#symload lctn with t1qag_get_lctn
#symload node with t1qag_get_node
(* ****** ****** *)
#symload lctn with t1iag_get_lctn
#symload node with t1iag_get_node
(* ****** ****** *)
#symload lctn with f1arg_get_lctn
#symload node with f1arg_get_node
(* ****** ****** *)
#symload lctn with d1gua_get_lctn
#symload node with d1gua_get_node
#symload lctn with d1gpt_get_lctn
#symload node with d1gpt_get_node
#symload lctn with d1cls_get_lctn
#symload node with d1cls_get_node
(* ****** ****** *)
#symload lctn with a1typ_get_lctn
#symload node with a1typ_get_node
#symload lctn with d1arg_get_lctn
#symload node with d1arg_get_node
(* ****** ****** *)

#implfun
d1pat_fprint
( d1p, out ) =
let
#impltmp
g_print$out<>() = out
in//let
//
case+
d1p.node() of
|
D1Pid0(id0) =>
(print("D1Pid0("); print(id0); print(")"))
//
|
D1Pint(int) =>
(print("D1Pint("); print(int); print(")"))
|
D1Pchr(chr) =>
(print("D1Pchr("); print(chr); print(")"))
|
D1Pflt(flt) =>
(print("D1Pflt("); print(flt); print(")"))
|
D1Pstr(str) =>
(print("D1Pstr("); print(str); print(")"))
//
|
D1Pb0sh
( (*0*) ) =>
(print("D1Pb0sh("); print(")"))
|
D1Pb1sh
(  d1p  ) =>
(print("D1Pb1sh("); print(d1p); print(")"))
//
(* ****** ****** *)
//
|D1Paspt
(tok, d1p) =>
(print("D1Paspt("); print(tok); print(";"); print(d1p); print(")"))
//
(* ****** ****** *)
//
|D1Pa0pp
( (*void*) ) =>
(
(print("D1Pa0pp("); print(")")))
|D1Pa1pp
(d1f0, d1p1) =>
(
(print("D1Pa1pp("); print(d1f0); print(";"); print(d1p1); print(")")))
|D1Pa2pp
(d1f0
,d1p1, d1p2) =>
(
print("D1Pa2pp(");
(print(d1f0); print(";"); print(d1p1); print(";"); print(d1p2); print(")")))
//
(* ****** ****** *)
//
|D1Psarg
(   s1as   ) =>
(
(print("D1Psarg("); print(s1as); print(")")))
//
(* ****** ****** *)
//
|D1Pl1st
(   d1ps   ) =>
(
(print("D1Pl1st("); print(d1ps); print(")")))
|D1Pl2st
(dps1, dps2) =>
(print("D1Pl2st("); print(dps1); print(";"); print(dps2); print(")"))
//
(* ****** ****** *)
//
|D1Pt1up
(tok0, d1ps) =>
(print("D1Pt1up("); print(tok0); print(";"); print(d1ps); print(")"))
|D1Pt2up
(tok0
,dps1, dps2) =>
(
print("D1Pt2up(");
(print(tok0); print(";"); print(dps1); print(";"); print(dps2); print(")")))
//
|
D1Pannot
(d1p1, s1e2) =>
(print("D1Pannot("); print(d1p1); print(";"); print(s1e2); print(")"))
|
D1Pqual0
(tok1, d1p2) =>
(print("D1Pqual0("); print(tok1); print(";"); print(d1p2); print(")"))
//
(*
|D1Pg1mac
(   gmac   ) =>
(
 prints(  "D1Pg1mac(" , gmac , ")"  ))
*)
//
|
D1Pnone0() => (print("D1Pnone0("); print(")"))
|
D1Pnone1(dpat) => (print("D1Pnone1("); print(dpat); print(")"))
//
|
D1Perrck // HX: generated by [tread01]
( lvl1
(*err-level*),d1p2) => (print("D1Perrck("); print(lvl1); print(";"); print(d1p2); print(")"))
//
end(*let*)//end-of-[implfun(d1pat_fprint(d1p,out))]

(* ****** ****** *)

#implfun
f1arg_fprint
( farg, out ) =
let
#impltmp
g_print$out<>() = out
in//let
//
case+
farg.node() of
|
F1ARGdapp(d1p1) =>
(
  (print("F1ARGdapp("); print(d1p1); print(")")) )
|
F1ARGsapp(s1qs) =>
(
  (print("F1ARGsapp("); print(s1qs); print(")")) )
|
F1ARGmets(s1es) =>
(
  (print("F1ARGmets("); print(s1es); print(")")) )
//
end (*let*) // end of [f1arg_fprint(farg,out)]

(* ****** ****** *)

#implfun
d1gua_fprint
( dgua, out ) =
let
#impltmp
g_print$out<>() = out
in//let
//
case+
dgua.node() of
|
D1GUAexp(d1e1) =>
(print("D1GUAexp("); print(d1e1); print(")"))
|
D1GUAmat(d1e1,d1p2) =>
(print("D1GUAmat("); print(d1e1); print(";"); print(d1p2); print(")"))
//
end (*let*) // end of [d1gua_fprint(dgua,out)]

(* ****** ****** *)
//
#implfun
d1cls_fprint
( dcls, out ) =
let
#impltmp
g_print$out<>() = out
in//let
case+
dcls.node() of
|
D1CLSgpt(dgpt) =>
(
  (print("D1CLSgpt("); print(dgpt); print(")")))
|
D1CLScls(d1g1,d1e2) =>
(
  (print("D1CLScls("); print(d1g1); print(";"); print(d1e2); print(")")))
end (*let*) // end of [d1cls_fprint(dcls,out)]
//
#implfun
d1gpt_fprint
( dgpt, out ) =
let
#impltmp
g_print$out<>() = out
in//let
case+
dgpt.node() of
|
D1GPTpat(d1p1) =>
(print("D1GPTpat("); print(d1p1); print(")"))
|
D1GPTgua(d1p1,d1gs) =>
(print("D1GPTgua("); print(d1p1); print(";"); print(d1gs); print(")"))
end (*let*) // end of [d1gpt_fprint(dgpt,out)]
//
(* ****** ****** *)
//
#implfun
d1exp_fprint
( d1e, out ) =
let
#impltmp
g_print$out<>() = out
in//let
//
case+
d1e.node() of
//
|
D1Eid0(id0) =>
(print("D1Eid0("); print(id0); print(")"))
//
|
D1Eint(int) =>
(print("D1Eint("); print(int); print(")"))
|
D1Echr(chr) =>
(print("D1Echr("); print(chr); print(")"))
|
D1Eflt(flt) =>
(print("D1Eflt("); print(flt); print(")"))
|
D1Estr(str) =>
(print("D1Estr("); print(str); print(")"))
//
|
D1Eb0sh(   ) =>
(print("D1Eb0sh("); print(")"))
|
D1Eb1sh(d1e) =>
(print("D1Eb1sh("); print(d1e); print(")"))
//
|
D1Ea0pp() =>
(print("D1Ea0pp("); print(")"))
|
D1Ea1pp
(d1f0,d1e1) =>
(print("D1Ea1pp("); print(d1f0); print(";"); print(d1e1); print(")"))
|
D1Ea2pp
(d1f0,d1e1,d1e2) =>
(print("D1Ea2pp("); print(d1f0); print(";"); print(d1e1); print(";"); print(d1e2); print(")"))
//
|
D1Esarg
(  s1es  ) =>
(print("D1Esarg("); print(s1es); print(")"))
|
D1Etarg
(  s1es  ) =>
(print("D1Etarg("); print(s1es); print(")"))
//
|
D1El1st
(  d1es  ) =>
(print("D1El1st("); print(d1es); print(")"))
|
D1El2st
(des1,des2) =>
(print("D1El2st("); print(des1); print(";"); print(des2); print(")"))
//
|
D1Es1eq
(  d1es  ) =>
(print("D1Es1eq("); print(d1es); print(")"))
|
D1Es2eq
(des1,des2) =>
(print("D1Es2eq("); print(des1); print(";"); print(des2); print(")"))
//
|
D1Eift0
(d1e1,dthn,dels) =>
(
print("D1Eift0(");
(print(d1e1); print(";"); print(dthn); print(";"); print(dels); print(")")))
//
|
D1Ecas0
(tknd,d1e1,d1cs) =>
(
print("D1Ecas0(");
(print(tknd); print(";"); print(d1e1); print(";"); print(d1cs); print(")")))
//
|
D1Elet0
(d1cs,d1e1) =>
(print("D1Elet0("); print(d1cs); print(";"); print(d1e1); print(")"))
//
|
D1Et1up
(tknd,d1es) =>
(
(print("D1Et1up("); print(tknd); print(";"); print(d1es); print(")")))
|
D1Et2up
(tknd,des1,des2) =>
( print("D1Et2up(")
; (print(tknd); print(";"); print(des1); print(";"); print(des2); print(")")))
//
|
D1Er1cd
(tknd,ldes) =>
(
(print("D1Er1cd("); print(tknd); print(";"); print(ldes); print(")")))
|
D1Er2cd
(tknd,lds1,lds2) =>
( print("D1Er2cd(")
; (print(tknd); print(";"); print(lds1); print(";"); print(lds2); print(")")))
//
|
D1Elam0
(tknd,f1as
,sres,arrw,d1e1) =>
(
(print("D1Elam0("); print(tknd); print(";"));
(print(f1as); print(";"); print(sres); print(";"); print(arrw); print(";"); print(d1e1); print(")")))
//
|
D1Efix0
(tknd,dpid,f1as
,sres,arrw,d1e1) =>
(
(print("D1Efix0("); print(tknd); print(";"); print(dpid); print(";"));
(print(f1as); print(";"); print(sres); print(";"); print(arrw); print(";"); print(d1e1); print(")")))
//
|
D1Etry0
(tknd,d1e1,d1cs) =>
(
print("D1Etry0(");
(print(tknd); print(";"); print(d1e1); print(";"); print(d1cs); print(")")))
//
|
D1Ewhere
(d1e1,d1cs) =>
(print("D1Ewhere("); print(d1e1); print(";"); print(d1cs); print(")"))
//
|
D1Ebrckt
(  d1es  ) =>
(print("D1Ebrckt("); print(d1es); print(")"))
|
D1Edtsel
(tknd,lab1,dopt) =>
( print("D1Edtsel(")
; (print(tknd); print(";"); print(lab1); print(";"); print(dopt); print(")")))
//
|
D1Eraise
(tknd,d1e1) =>
(print("D1Eraise("); print(tknd); print(";"); print(d1e1); print(")"))
//
|
D1Eannot
(d1e1,s1e2) =>
(print("D1Eannot("); print(d1e1); print(";"); print(s1e2); print(")"))
//
|
D1Equal0
(tok1,d1e2) =>
(print("D1Equal0("); print(tok1); print(";"); print(d1e2); print(")"))
//
(* ****** ****** *)
|
D1Eexists
(tknd,d1es,d1e1) =>
(print("D1Eexists("); print(tknd); print(";"); print(d1es); print(";"); print(d1e1); print(")"))
//
(* ****** ****** *)
//
(*
|
D1Eg1mac
( gmac ) => prints("D1Eg1mac(", gmac ,")")
*)
//
(* ****** ****** *)
//
|
D1Eextnam
(tknd,gnam) =>
(print("D1Eextnam("); print(tknd); print(";"); print(gnam); print(")"))
//
|
D1Esynext
(tknd,gexp) =>
(print("D1Esynext("); print(tknd); print(";"); print(gexp); print(")"))
//
(* ****** ****** *)
//
|D1Enone0() => (print("D1Enone0("); print(")"))
|D1Enone1(dexp) => (print("D1Enone1("); print(dexp); print(")"))
//
(* ****** ****** *)
//
|
D1Eerrck // HX: generated by [tread01]
( lvl1
(*err-level*),d1e2) => (print("D1Eerrck("); print(lvl1); print(";"); print(d1e2); print(")"))
//
(* ****** ****** *)
//
end(*let*)//end-of-[implfun(d1exp_fprint(d1e,out))]
//
(* ****** ****** *)
//
#implfun
d1ecl_fprint
( dcl, out ) =
let
#impltmp
g_print$out<>() = out
in//let
//
case+
dcl.node() of
//
|
D1Cd0ecl
( d0cl ) =>
(print("D1Cd0ecl("); print(d0cl); print(")"))
//
|
D1Cextern
(tknd,dcl1) =>
(print("D1Cextern("); print(tknd); print(";"); print(dcl1); print(")"))
|
D1Cstatic
(tknd,dcl1) =>
(print("D1Cstatic("); print(tknd); print(";"); print(dcl1); print(")"))
//
|
D1Cdefine
(tknd
,geid,gmas,gopt) =>
(
print("D1Cdefine(");
(print(tknd); print(";"); print(geid); print(";"); print(gmas); print(";"); print(gopt); print(")")))
|
D1Cmacdef
(tknd
,geid,gmas,dopt) =>
(
print("D1Cmacdef(");
(print(tknd); print(";"); print(geid); print(";"); print(gmas); print(";"); print(dopt); print(")")))
//
|
D1Clocal0
(head,body) =>
(
(print("D1Clocal0("); print(head); print(";"); print(body); print(")")))
//
|
D1Cabssort
(tknd,tid0) =>
(print("D1Cabssort("); print(tknd); print(";"); print(tid0); print(")"))
//
|
D1Cstacst0
(tknd
,sid0,tmas,s1t1) =>
(
print("D1Cstacst0(");
(print(tknd); print(";"); print(sid0); print(";"); print(tmas); print(";"); print(s1t1); print(")")))
//
|
D1Csortdef
(tknd,tid0,stdf) =>
(print("D1Csortdef("); print(tknd); print(";"); print(tid0); print(";"); print(stdf); print(")"))
//
|
D1Csexpdef
(tknd,seid
,smas,tres,s1e1) =>
(
(print("D1Csexpdef("); print(tknd); print(";"));
(print(seid); print(";"); print(smas); print(";"); print(tres); print(";"); print(s1e1); print(")")))
//
|
D1Cabstype
(tknd,seid
,tmas,tres,atdf) =>
(
(print("D1Cabstype("); print(tknd); print(";"));
(print(seid); print(";"); print(tmas); print(";"); print(tres); print(";"); print(atdf); print(")")))
|
D1Cabsopen
(  tknd, sqid  ) =>
(print("D1Cabsopen("); print(tknd); print(";"); print(sqid); print(")"))
|
D1Cabsimpl
(tknd,sid1
,smas,tres,sdef) =>
(
(print("D1Cabsimpl("); print(tknd); print(";"));
(print(sid1); print(";"); print(smas); print(";"); print(tres); print(";"); print(sdef); print(")")))
//
|
D1Csymload
(tknd
,deid,dqid,gopt) =>
(
print
("D1Csymload(");
(print(tknd); print(";"); print(deid); print(";"); print(dqid); print(";"); print(gopt); print(")")))
//
|
D1Cinclude
(knd0,tknd
,g1e1,fopt,dopt) =>
(
(*
prints("\n\
D1Cinclude: dopt =", "\n", dopt, "\n")
*)
) where
{
val () =
(
print
("D1Cinclude(");
(print(knd0); print(";"); print(tknd); print(";"); print(g1e1); print(";"); print(fopt); print(";"); print("..."); print(")")))
}
|
D1Cstaload
(knd0,tknd
,g1e1,fopt,dopt) =>
(
(*
prints("\n\
D1Cstaload: dopt =", "\n", dopt, "\n")
*)
) where
{
val () =
(
print
("D1Cstaload(");
(print(knd0); print(";"); print(tknd); print(";"); print(g1e1); print(";"); print(fopt); print(";"); print("..."); print(")")))
}
//
(* ****** ****** *)
|
D1Cdyninit(tknd,g1e1) =>
(
(print("D1Cdyninit("); print(tknd); print(";"); print(g1e1); print(")")))
//
(* ****** ****** *)
//
(*
HX-2024-07-20:
Sat 20 Jul 2024 01:33:42 PM EDT
*)
|
D1Cextcode(tknd,g1e1) =>
(
(print("D1Cextcode("); print(tknd); print(";"); print(g1e1); print(")")))
//
(* ****** ****** *)
//
|
D1Cdatasort
(  tknd, dtcs  ) =>
(
(print("D1Cdatasort("); print(tknd); print(";"); print(dtcs); print(")")))
//
|
D1Cvaldclst
(  tknd, d1vs  ) =>
(
(print("D1Cvaldclst("); print(tknd); print(";"); print(d1vs); print(")")))
|
D1Cvardclst
(  tknd, d1vs  ) =>
(
(print("D1Cvardclst("); print(tknd); print(";"); print(d1vs); print(")")))
//
|
D1Cfundclst
(tknd,tqas,d1fs) =>
(print("D1Cfundclst("); print(tknd); print(";"); print(tqas); print(";"); print(d1fs); print(")"))
//
|
D1Cimplmnt0
(tknd
,s0qs,t0qs
,dqid,t0is
,farg,sres,d0e2) =>
(
print("D1Cimplmnt0(");
(print(tknd); print(";"); print(s0qs); print(";"); print(t0qs); print(";"));
(print(dqid); print(";"); print(t0is); print(";"); print(farg); print(";"); print(sres); print(";"); print(d0e2); print(")")))
//
|
D1Cexcptcon
(tknd,dtcs) =>
(print("D1Cexcptcon("); print(tknd); print(";"); print(dtcs); print(")"))
|
D1Cdatatype
(tknd,d1ts,wdcs) =>
(print("D1Cdatatype("); print(tknd); print(";"); print(d1ts); print(";"); print(wdcs); print(")"))
//
|
D1Cdynconst
(tknd,tqas,d1cs) =>
(print("D1Cdynconst("); print(tknd); print(";"); print(tqas); print(";"); print(d1cs); print(")"))
//
|D1Cnone0() => (print("D1Cnone0("); print(")"))
|D1Cnone1(d0cl) => (print("D1Cnone1("); print(d0cl); print(")"))
//
(* ****** ****** *)
//
(*
HX-2025-04-19:
These are temporary constructs
generated during trans01_dparsed!
*)
|D1Cendif(tend) => (print("D1Cendif("); print(tend); print(")"))
|D1Cthen0(dcls) => (print("D1Cthen0("); print(dcls); print(")"))
|D1Celse1(dcls) => (print("D1Celse1("); print(dcls); print(")"))
|D1Cifexp
(gexp,dthn,dels,dend) =>
(print("D1Cifexp("); print(gexp); print(";"); print(dthn); print(";"); print(dels); print(";"); print(dend); print(")"))
|D1Celsif
(gexp,dthn,dels,dend) =>
(print("D1Celsif("); print(gexp); print(";"); print(dthn); print(";"); print(dels); print(";"); print(dend); print(")"))
//
(* ****** ****** *)
//
|
D1Cerrck // HX: generated by [tread01]
( lvl1
(*err-level*),d1cl) => (print("D1Cerrck("); print(lvl1); print(";"); print(d1cl); print(")"))
//
end(*let*)//end-of-[implfun(d1ecl_fprint(dcl,out))]
//
(* ****** ****** *)
//
#implfun
q1arg_fprint
( q1a, out ) =
let
#impltmp
g_print$out<>() = out
in//in-of-let
case+
q1a.node() of
|
Q1ARGsome(sid,opt) =>
(
(print("Q1ARGsome("); print(sid); print(";"); print(opt); print(")")))
end (*let*) // end of [q1arg_fprint(q1a,out)]
//
(* ****** ****** *)
//
#implfun
s1qag_fprint
( sqa, out ) =
let
#impltmp
g_print$out<>() = out
in//in-of-let
case+
sqa.node() of
|
S1QAGsome
(  sqs  ) => (print("S1QAGsome("); print(sqs); print(")"))
end (*let*) // end of [s1qag_fprint(sqa,out)]
//
(* ****** ****** *)
//
#implfun
t1qag_fprint
( tqa, out ) =
let
#impltmp
g_print$out<>() = out
in//in-of-let
case+
tqa.node() of
|
T1QAGsome
(  tqs  ) => (print("T1QAGsome("); print(tqs); print(")"))
end (*let*) // end of [t1qag_fprint(tqa,out)]
//
(* ****** ****** *)
//
#implfun
t1iag_fprint
( tia, out ) =
let
#impltmp
g_print$out<>() = out
in//in-of-let
case+
tia.node() of
|
T1IAGsome
(  ses  ) => (print("T1IAGsome("); print(ses); print(")"))
end (*let*) // end of [t1iag_fprint(tia,out)]
//
(* ****** ****** *)
//
#implfun
a1typ_fprint
( a1t, out ) =
let
#impltmp
g_print$out<>() = out
in//in-of-let
//
case+
a1t.node() of
|
A1TYPsome(s0e1,topt) =>
(print("A1TYPsome("); print(s0e1); print(";"); print(topt); print(")"))
end (*let*) // end of [a1typ_fprint(a1t,out)]
//
(* ****** ****** *)
//
#implfun
d1arg_fprint
( d1a, out ) =
let
#impltmp
g_print$out<>() = out
in//let
//
case+
d1a.node() of
|
D1ARGsta0(sqas) =>
(print("D1ARGsta0("); print(sqas); print(")"))
|
D1ARGdyn1
(  dpid  ) =>
(print("D1ARGdyn1("); print(dpid); print(")"))
|
D1ARGdyn2(a1ts,atsq) =>
(print("D1ARGdyn2("); print(";"); print(a1ts); print(";"); print(atsq); print(")"))
//
end (*let*) // end of [d1arg_fprint(d1a,out)]
//
(* ****** ****** *)
//
#implfun
a1tdf_fprint
( tdf, out ) =
let
#impltmp
g_print$out<>() = out
in//let
//
case+ tdf of
|
A1TDFsome() =>
(
  (print("A1TDFsome("); print(")")))
|
A1TDFlteq(s1e1) =>
(
  (print("A1TDFlteq("); print(s1e1); print(")")))
|
A1TDFeqeq(s1e1) =>
(
  (print("A1TDFeqeq("); print(s1e1); print(")")))
//
end (*let*) // end of [a1tdf_fprint(tdf,out)]
//
(* ****** ****** *)
//
#implfun
s1eff_fprint
( seff, out0 ) =
let
#implfun
g_print$out<>() = out0
in//let
case+ seff of
|
S1EFFnone() =>
(print("S1EFFnone("); print(")"))
|
S1EFFsome(s1fs) =>
(print("S1EFFsome("); print(s1fs); print(")"))
end (*let*) // end of [s1eff_fprint(seff,out0)]
//
#implfun
s1res_fprint
( sres, out0 ) =
let
#implfun
g_print$out<>() = out0
in//let
case+ sres of
|
S1RESnone() =>
(print("S1RESnone("); print(")"))
|
S1RESsome(seff, s1e1) =>
(print("S1RESsome("); print(seff); print(";"); print(s1e1); print(")"))
end (*let*) // end of [s1res_fprint(sres,out0)]
//
(* ****** ****** *)
//
#implfun
t1qua_fprint
( tqua, out0 ) =
let
#impltmp
g_print$out<>() = out0
in//let
case+ tqua of
|
T1QUAsome
(loc0, s1qs) =>
(print("T1QUAsome("); print(s1qs); print(")"))
end (*let*) // end of [t1qua_fprint(tqua,out0)]
//
#implfun
t1inv_fprint
( tinv, out0 ) =
let
#impltmp
g_print$out<>() = out0
in//let
case+ tinv of
|
T1INVsome
(loc0, tqas,d1ps) =>
(print("T1INVsome("); print(tqas); print(";"); print(d1ps); print(")"))
end (*let*) // end of [t1inv_fprint(tinv,out0)]
//
(* ****** ****** *)
//
#implfun
f1unarrw_fprint
 ( arrw, out0 ) =
let
#impltmp
g_print$out<>() = out0
in//let
//
case+ arrw of
|
F1UNARRWdflt
(   loc0   ) =>
(
  (print("F1UNARRWdflt("); print(")")))
|
F1UNARRWlist
(loc0, s1es) =>
(
  (print("F1UNARRWlist("); print(s1es); print(")")))
//
end(*let*)//end-of-[f1unarrw_fprint(arrw,out0)]
//
(* ****** ****** *)
//
#implfun
wd1eclseq_fprint
 ( wdcs, out0 ) =
let
#impltmp
g_print$out<>() = out0
in//let
//
case+ wdcs of
|
WD1CSnone() => (print("WD1CSnone("); print(")"))
|
WD1CSsome(dcls) => (print("WD1CSsome("); print(dcls); print(")"))
//
end(*let*)//end-of-[wd1eclseq_fprint(wdcs,out0)]
//
(* ****** ****** *)

#implfun
d1valdcl_fprint
 (dval, out0) = let
//
val dpat =
d1valdcl_get_dpat(dval)
val tdxp =
d1valdcl_get_tdxp(dval)
val wsxp =
d1valdcl_get_wsxp(dval)
//
#impltmp g_print$out<>() = out0
//
in//let
(
(print("D1VALDCL("); print(dpat); print(";"); print(tdxp); print(";"); print(wsxp); print(")")))
end(*let*)//end-of-[d1valdcl_fprint(dval,out0)]

(* ****** ****** *)

#implfun
d1vardcl_fprint
  (dvar, out0) = let
//
val dpid =
d1vardcl_get_dpid(dvar)
val vpid =
d1vardcl_get_vpid(dvar)
val sres =
d1vardcl_get_sres(dvar)
val dini =
d1vardcl_get_dini(dvar)
//
#impltmp g_print$out<>() = out0
//
in//let
(
print("D1VARDCL(");
(print(dpid); print(";"); print(vpid); print(";"); print(sres); print(";"); print(dini); print(")")))
end(*let*)//end-of-[d1vardcl_fprint(dvar,out0)]

(* ****** ****** *)

#implfun
d1fundcl_fprint
  (dfun, out0) = let
//
val dpid =
d1fundcl_get_dpid(dfun)
val farg =
d1fundcl_get_farg(dfun)
val sres =
d1fundcl_get_sres(dfun)
val tdxp =
d1fundcl_get_tdxp(dfun)
val wsxp =
d1fundcl_get_wsxp(dfun)
//
#impltmp g_print$out<>() = out0
//
in//let
(
(print("D1FUNDCL("); print(dpid); print(";"));
(print(farg); print(";"); print(sres); print(";"); print(tdxp); print(";"); print(wsxp); print(")")))
end(*let*)//end-of-[d1fundcl_fprint(dfun,out0)]

(* ****** ****** *)

#implfun
d1cstdcl_fprint
  (dcst, out0) =
let
//
(*
val lctn = dcst.lctn()
*)
val dpid =
d1cstdcl_get_dpid(dcst)
val darg =
d1cstdcl_get_darg(dcst)
val sres =
d1cstdcl_get_sres(dcst)
val dres =
d1cstdcl_get_dres(dcst)
//
#impltmp g_print$out<>() = out0
//
in//let
(print("D1CSTDCL("); print(dpid); print(";"); print(darg); print(";"); print(sres); print(";"); print(dres); print(")"))
end(*let*)//end-of-[d1cstdcl_fprint(dcst,out0)]

(* ****** ****** *)
//
#implfun
d1parsed_fprint
  (dpar, out0) = let
//
val
stadyn =
d1parsed_get_stadyn(dpar)
val
nerror =
d1parsed_get_nerror(dpar)
val
source =
d1parsed_get_source(dpar)
val
parsed =
d1parsed_get_parsed(dpar)
//
#impltmp g_print$out<>() = out0
//
in//let
(
print("D1PARSED(");
(print(stadyn); print(";"); print(nerror); print(";"); print(source); print(";"); print(parsed); print(")")))
end (*let*) // end-of-[d1parsed_fprint(dpar,out0)]
//
(* ****** ****** *)
(* ****** ****** *)
//
(***********************************************************************)
(* end of [ATS3/XATSOPT_srcgen2_DATS_dynexp1_print0.dats] *)
(***********************************************************************)
