(***********************************************************************)
(*                                                                     *)
(*                         Applied Type System                         *)
(*                                                                     *)
(***********************************************************************)

(*
** ATS/Xanadu - Unleashing the Potential of Types!
** Copyright (C) 2022 Hongwei Xi, ATS Trustful Software, Inc.
** All rights reserved
**
** ATS is free software;  you can  redistribute it and/or modify it under
** the terms of  the GNU GENERAL PUBLIC LICENSE (GPL) as published by the
** Free Software Foundation; either version 3, or (at  your  option)  any
** later version.
** 
** ATS is distributed in the hope that it will be useful, but WITHOUT ANY
** WARRANTY; without  even  the  implied  warranty  of MERCHANTABILITY or
** FITNESS FOR A PARTICULAR PURPOSE.  See the  GNU General Public License
** for more details.
** 
** You  should  have  received  a  copy of the GNU General Public License
** along  with  ATS;  see the  file COPYING.  If not, please write to the
** Free Software Foundation,  51 Franklin Street, Fifth Floor, Boston, MA
** 02110-1301, USA.
*)

(* ****** ****** *)
//
(*
Author: Hongwei Xi
Start Time: June 19th, 2022
Authoremail: gmhwxiATgmailDOTcom
*)
//
(* ****** ****** *)
(* ****** ****** *)
#define
ATS_PACKNAME
"ATS3.XANADU.xatsopt-20220500"
(* ****** ****** *)
(* ****** ****** *)
//
#include
"./../HATS/xatsopt_sats.hats"
#include
"./../HATS/xatsopt_dpre.hats"
//
(* ****** ****** *)
(* ****** ****** *)
#staload "./../SATS/locinfo.sats"
(* ****** ****** *)
#staload "./../SATS/lexing0.sats"
(* ****** ****** *)
#staload "./../SATS/staexp0.sats"
#staload "./../SATS/dynexp0.sats"
(* ****** ****** *)
#symload node with q0arg_get_node
#symload node with s0qag_get_node
#symload node with t0qag_get_node
#symload node with t0iag_get_node
(* ****** ****** *)
#symload node with d0exp_get_node
#symload node with d0pat_get_node
#symload node with d0ecl_get_node
(* ****** ****** *)
#symload dpid with d0cstdcl_get_dpid
#symload darg with d0cstdcl_get_darg
#symload sres with d0cstdcl_get_sres
#symload dres with d0cstdcl_get_dres
(* ****** ****** *)
#symload dpat with d0valdcl_get_dpat
#symload wsxp with d0valdcl_get_wsxp
#symload tdxp with d0valdcl_get_tdxp
(* ****** ****** *)
#symload dpid with d0vardcl_get_dpid
#symload vpid with d0vardcl_get_vpid
#symload sres with d0vardcl_get_sres
#symload dini with d0vardcl_get_dini
(* ****** ****** *)
#symload dpid with d0fundcl_get_dpid
#symload farg with d0fundcl_get_farg
#symload sres with d0fundcl_get_sres
#symload tdxp with d0fundcl_get_tdxp
#symload wsxp with d0fundcl_get_wsxp
(* ****** ****** *)

#implfun
d0pat_fprint
( d0p, out ) =
let
#impltmp
g_print$out<>() = out
in//let
//
case+
d0p.node() of
//
|
D0Pid0(id0) =>
(print("D0Pid0("); print(id0); print(")"))
//
|
D0Pint(int) =>
(print("D0Pint("); print(int); print(")"))
|
D0Pchr(chr) =>
(print("D0Pchr("); print(chr); print(")"))
|
D0Pflt(flt) =>
(print("D0Pflt("); print(flt); print(")"))
|
D0Pstr(str) =>
(print("D0Pstr("); print(str); print(")"))
//
|
D0Paspt
(tknd, d0p1) =>
(print("D0Paspt("); print(tknd); print(";"); print(d0p1); print(")"))
//
|
D0Papps(d0ps) =>
(
  (print("D0Papps("); print(d0ps); print(")")))
//
|
D0Psarg
(tbeg,s0as,tend) =>
(print("D0Psarg("); print(tbeg); print(";"); print(s0as); print(";"); print(tend); print(")"))
//
|
D0Plpar
(tbeg,t0ps,tend) =>
(print("D0Plpar("); print(tbeg); print(";"); print(t0ps); print(";"); print(tend); print(")"))
//
|
D0Ptup1
(tbeg,topt,d0ps,tend) =>
(
print("D0Ptup1(");
(print(tbeg); print(";"); print(topt); print(";"); print(d0ps); print(";"); print(tend); print(")")))
|
D0Prcd2
(tbeg,topt,ldps,tend) =>
(
print("D0Prcd2(");
(print(tbeg); print(";"); print(topt); print(";"); print(ldps); print(";"); print(tend); print(")")))
//
|
D0Pannot(d0p1,s0e2) =>
(print("D0Pannot("); print(d0p1); print(";"); print(s0e2); print(")"))
//
|
D0Ptkerr(tok) => (print("D0Ptkerr("); print(tok); print(")"))
|
D0Perrck // HX: generated by [pread00]
(lvl1(*err-level*),d0p2) => (print("D0Perrck("); print(lvl1); print(";"); print(d0p2); print(")"))
//
end (*let*) // end of [d0pat_fprint(d0p,out)]

(* ****** ****** *)

#implfun
f0arg_fprint
( f0a, out ) =
let
#impltmp
g_print$out<>() = out
in//let
//
case+
f0a.node() of
|
F0ARGnone(tok) =>
(print("F0ARGnone("); print(tok); print(")"))
|
F0ARGdapp(d0p) =>
(print("F0ARGdapp("); print(d0p); print(")"))
|
F0ARGsapp(tkb,sqs,tke) =>
(print("F0ARGsapp("); print(tkb); print(";"); print(sqs); print(";"); print(tke); print(")"))
|
F0ARGmets(tkb,ses,tke) =>
(print("F0ARGmets("); print(tkb); print(";"); print(ses); print(";"); print(tke); print(")"))
//
end (*let*) // end of [f0arg_fprint(f0a,out)]

(* ****** ****** *)

#implfun
d0gua_fprint
( dgua, out ) =
let
#impltmp
g_print$out<>() = out
in//let
//
case+
dgua.node() of
|
D0GUAexp(d0e1) =>
(print("D0GUAexp("); print(d0e1); print(")"))
|
D0GUAmat(d0e1,tkas,d0p2) =>
(
(print("D0GUAmat("); print(d0e1); print(";"); print(tkas); print(";"); print(d0p2); print(")")))
//
end (*let*) // end of [d0gua_fprint(dgua,out)]

(* ****** ****** *)
//
#implfun
d0cls_fprint
( dcls, out ) =
let
#impltmp
g_print$out<>() = out
in//let
case+
dcls.node() of
|
D0CLSgpt(dgpt) =>
(print("D0CLSgpt("); print(dgpt); print(")"))
|
D0CLScls
(d0g1,tsep,d0e2) =>
(
(print("D0CLScls("); print(d0g1); print(";"); print(tsep); print(";"); print(d0e2); print(")")))
end (*let*) // end of [d0cls_fprint(dcls,out)]
//
#implfun
d0gpt_fprint
( dgpt, out ) =
let
#impltmp
g_print$out<>() = out
in//let
case+
dgpt.node() of
|
D0GPTpat(d0p1) =>
(print("D0GPTpat("); print(d0p1); print(")"))
|
D0GPTgua
(d0p1,tsep,d0gs) =>
(
(print("D0GPTgua("); print(d0p1); print(";"); print(tsep); print(";"); print(d0gs); print(")")))
end (*let*) // end of [d0gpt_fprint(dgpt,out)]
//
(* ****** ****** *)

#implfun
d0exp_fprint
( d0e, out ) =
let
#impltmp
g_print$out<>() = out
in//let
//
case+
d0e.node() of
//
|
D0Eid0(id0) =>
(print("D0Eid0("); print(id0); print(")"))
//
|
D0Eint(int) =>
(print("D0Eint("); print(int); print(")"))
|
D0Echr(chr) =>
(print("D0Echr("); print(chr); print(")"))
|
D0Eflt(flt) =>
(print("D0Eflt("); print(flt); print(")"))
|
D0Estr(str) =>
(print("D0Estr("); print(str); print(")"))
//
|
D0Eapps(d0es) =>
(print("D0Eapps("); print(d0es); print(")"))
//
|
D0Esarg
(tbeg,s0es,tend) =>
(print("D0Esarg("); print(tbeg); print(";"); print(s0es); print(";"); print(tend); print(")"))
|
D0Etarg
(tbeg,s0es,tend) =>
(print("D0Etarg("); print(tbeg); print(";"); print(s0es); print(";"); print(tend); print(")"))
//
|
D0Elpar
(tbeg,d0es,tend) =>
(print("D0Elpar("); print(tbeg); print(";"); print(d0es); print(";"); print(tend); print(")"))
//
|
D0Eift0
(tknd,d0e1,dthn,dels) =>
(
(print("D0Eift0("); print(tknd); print(";"));
(print(d0e1); print(";"); print(dthn); print(";"); print(dels); print(")")))
|
D0Eift1
(tknd,d0e1,dthn,dels,tinv) =>
(
(print("D0Eift1("); print(tknd); print(";"));
(print(d0e1); print(";"); print(dthn); print(";"); print(dels); print(";"); print(tinv); print(")")))
//
|
D0Ecas0
(tknd,d0e1,tof0,tbar,dcls) =>
(
(print("D0Ecas0("); print(tknd); print(";"));
(print(d0e1); print(";"); print(tof0); print(";"); print(tbar); print(";"); print(dcls); print(")")))
|
D0Ecas1
(tknd
,d0e1,tof0,tbar,dcls,tinv) =>
(
(print("D0Ecas1("); print(tknd); print(";"); print(d0e1); print(";"));
(print(tof0); print(";"); print(tbar); print(";"); print(dcls); print(";"); print(tinv); print(")")))
//
|
D0Etup1
(tbeg,topt,d0es,tend) =>
(
print("D0Etup1(");
(print(tbeg); print(";"); print(topt); print(";"); print(d0es); print(";"); print(tend); print(")")))
|
D0Ercd2
(tbeg,topt,ldes,tend) =>
(
print("D0Ercd2(");
(print(tbeg); print(";"); print(topt); print(";"); print(ldes); print(";"); print(tend); print(")")))
//
|
D0Elet0
(tknd,dcls,topt,d0es,tend) =>
(
(print("D0Elet0("); print(tknd); print(";"));
(print(dcls); print(";"); print(topt); print(";"); print(d0es); print(";"); print(tend); print(")")))
//
|
D0Etry0
(tknd
,d0es,twth,tbar,dcls,tend) =>
//
(
(print("D0Etry0("); print(tknd); print(";"); print(d0es); print(";"));
(print(twth); print(";"); print(tbar); print(";"); print(dcls); print(";"); print(tend); print(")")))
|
D0Elam0
(tknd
,farg,sres,arrw,body,tend) =>
(
(print("D0Elam0("); print(tknd); print(";"); print(farg); print(";"));
(print(sres); print(";"); print(arrw); print(";"); print(body); print(";"); print(tend); print(")")))
//
|
D0Efix0
(tknd,dpid
,farg,sres,arrw,body,tend) =>
(
print
("D0Efix0(");
(print(tknd); print(";"); print(dpid); print(";"); print(farg); print(";"));
(print(sres); print(";"); print(arrw); print(";"); print(body); print(";"); print(tend); print(")")))
//
|
D0Ewhere(d0e1,dcl2) =>
(print("D0Ewhere("); print(d0e1); print(";"); print(dcl2); print(")"))
//
|
D0Ebrckt
(tbeg, d0es, tend) =>
(print("D0Ebrckt("); print(tbeg); print(";"); print(d0es); print(";"); print(tend); print(")"))
|
D0Edtsel
(tknd, lab1, opt2) =>
(print("D0Edtsel("); print(tknd); print(";"); print(lab1); print(";"); print(opt2); print(")"))
//
|
D0Eraise(tknd,d0e1) =>
(print("D0Eraise("); print(tknd); print(";"); print(d0e1); print(")"))
//
|
D0Eannot(d0e1,s0e2) =>
(print("D0Eannot("); print(d0e1); print(";"); print(s0e2); print(")"))
//
|
D0Equal0(tok1,d0e2) =>
(print("D0Equal0("); print(tok1); print(";"); print(d0e2); print(")"))
//
|
D0Eexists
(tknd,d0es,d0e1) =>
(print("D0Eexists("); print(tknd); print(";"); print(d0es); print(";"); print(d0e1); print(")"))
//
(* ****** ****** *)
//
|
D0Eextnam
(tknd,gnam) =>
(print("D0Eextnam("); print(tknd); print(";"); print(gnam); print(")"))
//
|
D0Esynext
(tknd,gexp) =>
(print("D0Esynext("); print(tknd); print(";"); print(gexp); print(")"))
//
(* ****** ****** *)
//
|
D0Etkerr(terr) => (print("D0Etkerr("); print(terr); print(")"))
//
|
D0Eerrck // HX: generated by [pread00]
(lvl1(*err-level*),d0e2) => (print("D0Eerrck("); print(lvl1); print(";"); print(d0e2); print(")"))
//
end (*let*) // end of [ d0exp_fprint(d0e,out) ]

(* ****** ****** *)
//
#implfun
t0qua_fprint
( tqua, out ) =
let
#impltmp
g_print$out<>() = out
in//let
//
case+ tqua of
|
T0QUAnone(terr) =>
(print("T0QUAnone("); print(terr); print(")"))
|
T0QUAsome(tbeg,s0qs,tend) =>
(print("T0QUAsome("); print(tbeg); print(";"); print(s0qs); print(";"); print(tend); print(")"))
//
end (*let*) // end of [t0qua_fprint(tqua,out)]
#implfun
t0inv_fprint
( tinv, out ) =
let
#impltmp
g_print$out<>() = out
in//let
case+ tinv of
|
T0INVnone(tqua,terr) =>
(print("T0INVnone("); print(tqua); print(";"); print(terr); print(")"))
|
T0INVsome(tqas,tbeg,d0ps,tend) =>
(
print("T0INVsome(");
(print(tqas); print(";"); print(tbeg); print(";"); print(d0ps); print(";"); print(tend); print(")")))
end (*let*) // end of [t0inv_fprint(tinv,out)]
//
(* ****** ****** *)

#implfun
f0unarrw_fprint
  (arrw, out) =
let
#impltmp
g_print$out<>() = out
in//let
//
case+ arrw of
|
F0UNARRWnone(tok) =>
(print("F0UNARRWnone("); print(tok); print(")"))
|
F0UNARRWdflt(tok) =>
(print("F0UNARRWdflt("); print(tok); print(")"))
|
F0UNARRWlist(tkb,ses,tke) =>
(
(print("F0UNARRWlist("); print(tkb); print(";"); print(ses); print(";"); print(tke); print(")")))
//
end (*let*)//end-of-[f0unarrw_fprint(arrw,out)]

(* ****** ****** *)

#implfun
d0exp_THEN_fprint
  ( gthn, out ) =
(
case+ gthn of
|
d0exp_THEN_none(tok) =>
(print("d0exp_THEN_none("); print(tok); print(")"))
|
d0exp_THEN_some(tok,d0e) =>
(print("d0exp_THEN("); print(tok); print(";"); print(d0e); print(")"))
) where
{
#impltmp g_print$out<>() = out
} (*where*) // end of [d0exp_THEN_fprint(...)]
#implfun
d0exp_ELSE_fprint
  ( gels, out ) =
(
case+ gels of
|
d0exp_ELSE_none(tok) =>
(print("d0exp_ELSE_none("); print(tok); print(")"))
|
d0exp_ELSE_some(tok, d0e) =>
(print("d0exp_ELSE_some("); print(tok); print(";"); print(d0e); print(")"))
) where
{
#impltmp g_print$out<>() = out
} (*where*) // end of [d0exp_ELSE_fprint(...)]

(* ****** ****** *)

#implfun
d0pat_RPAREN_fprint
  ( drp, out ) =
let
#impltmp
g_print$out<>() = out
in//let
case+ drp of
|
d0pat_RPAREN_cons0(tbar) =>
(print("d0pat_RPAREN_cons0("); print(tbar); print(")"))
|
d0pat_RPAREN_cons1(tok1, d0ps, tok2) =>
(
(print("d0pat_RPAREN_cons1("); print(tok1); print(";"); print(d0ps); print(";"); print(tok2); print(")")))
end (*let*) // end of [d0pat_RPAREN_fprint(drp,out)]

(* ****** ****** *)

#implfun
l0d0p_RBRACE_fprint
  (ldrb, out) =
let
//
#impltmp
g_print$out<>() = out
//
in//let
case+ ldrb of
|
l0d0p_RBRACE_cons0(tbar) =>
(print("l0d0p_RBRACE_cons0("); print(tbar); print(")"))
|
l0d0p_RBRACE_cons1(tok1, lses, tok2) =>
(
(print("l0d0p_RBRACE_cons1("); print(tok1); print(";"); print(lses); print(";"); print(tok2); print(")")))
end (*let*) // end of [l0d0p_RBRACE_fprint(ldrb,out)]

(* ****** ****** *)

#implfun
d0exp_RPAREN_fprint
  ( drp, out ) =
let
#impltmp
g_print$out<>() = out
in//let
case+ drp of
|
d0exp_RPAREN_cons0(tbar) =>
(print("d0exp_RPAREN_cons0("); print(tbar); print(")"))
|
d0exp_RPAREN_cons1(tok1, d0es, tok2) =>
(print("d0exp_RPAREN_cons1("); print(tok1); print(";"); print(d0es); print(";"); print(tok2); print(")"))
|
d0exp_RPAREN_cons2(tok1, d0es, tok2) =>
(print("d0exp_RPAREN_cons2("); print(tok1); print(";"); print(d0es); print(";"); print(tok2); print(")"))
end (*let*) // end of [d0exp_RPAREN_fprint(drp,out)]

(* ****** ****** *)

#implfun
l0d0e_RBRACE_fprint
  ( ldrb, out ) =
let
//
#impltmp
g_print$out<>() = out
//
in//let
case+ ldrb of
|
l0d0e_RBRACE_cons0(tbar) =>
(print("l0d0e_RBRACE_cons0("); print(tbar); print(")"))
|
l0d0e_RBRACE_cons1(tok1, lses, tok2) =>
(
(print("l0d0e_RBRACE_cons1("); print(tok1); print(";"); print(lses); print(";"); print(tok2); print(")")))
end (*let*) // end of [l0d0e_RBRACE_fprint(ldrb,out)]

(* ****** ****** *)

#implfun
d0ecl_fprint
( dcl, out ) =
let
#impltmp
g_print$out<>() = out
in//let
//
case+
dcl.node() of
//
|
D0Ctkerr(tok) =>
(print("D0Ctkerr("); print(tok); print(")"))
|
D0Ctkskp(tok) =>
(print("D0Ctkskp("); print(tok); print(")"))
//
|
D0Cnonfix
(tknd,dnts) =>
(print("D0Cnonfix("); print(tknd); print(";"); print(dnts); print(")"))
|
D0Cfixity
(tknd,dnts,prec) =>
(print("D0Cfixity("); print(tknd); print(";"); print(dnts); print(";"); print(prec); print(")"))
//
|
D0Cstatic
(tknd,dcl1) =>
(
  (print("D0Cstatic("); print(tknd); print(";"); print(dcl1); print(")")))
|
D0Cextern
(tknd,dcl1) =>
(
  (print("D0Cextern("); print(tknd); print(";"); print(dcl1); print(")")))
//
|
D0Cdefine
(tknd,geid,gmas,gedf) =>
(
(print("D0Cdefine("));
(print(tknd); print(";"); print(geid); print(";"); print(gmas); print(";"); print(gedf); print(")")))
|
D0Cmacdef
(tknd,geid,gmas,dedf) =>
(
(print("D0Cmacdef("));
(print(tknd); print(";"); print(geid); print(";"); print(gmas); print(";"); print(dedf); print(")")))
//
|
D0Clocal0
(tknd
,head,tin1,body,tend) =>
(
(print("D0Clocal0("); print(tknd); print(";"));
(print(head); print(";"); print(tin1); print(";"); print(body); print(";"); print(tend); print(")")))
//
|
D0Cabssort
(tknd,tid0) =>
(
  (print("D0Cabssort("); print(tknd); print(";"); print(tid0); print(")")))
|
D0Cstacst0
(tknd
,seid,tmas,tcln,s0t0) =>
(
(print("D0Cstacst0("); print(tknd); print(";"));
(print(seid); print(";"); print(tmas); print(";"); print(tcln); print(";"); print(s0t0); print(")")))
|
D0Csortdef
(tknd,tid0,teq1,def2) =>
(print("D0Csortdef("); print(tknd); print(";"); print(tid0); print(";"); print(teq1); print(";"); print(def2); print(")"))
//
|
D0Csexpdef
(tknd,sid0,smas,tres,teq1,def2) =>
(
(print("D0Csexpdef("); print(tknd); print(";"));
(print(sid0); print(";"); print(smas); print(";"); print(tres); print(";"));(print(teq1); print(";"); print(def2); print(")")))
//
|
D0Cabstype
(tknd,seid,tmas,tres,atdf) =>
(
(print("D0Cabstype("); print(tknd); print(";"));
(print(seid); print(";"); print(tmas); print(";"); print(tres); print(";"); print(atdf); print(")")))
|
D0Cabsopen(tknd, sqid) =>
(print("D0Cabsopen("); print(tknd); print(";"); print(sqid); print(")"))
|
D0Cabsimpl
(tknd,sid0,smas,tres,teq1,def2) =>
(
(print("D0Cabsimpl("); print(tknd); print(";"));
(print(sid0); print(";"); print(smas); print(";"); print(tres); print(";"));(print(teq1); print(";"); print(def2); print(")")))
//
|
D0Csymload
(tknd,symb,twth,dqid,pval) =>
(
(print("D0Csymload("); print(tknd); print(";"));
(print(symb); print(";"); print(twth); print(";"); print(dqid); print(";"); print(pval); print(")")))
//
|
D0Cinclude
(knd0,tknd,g0e1) =>
(print("D0Cinclude("); print(knd0); print(";"); print(tknd); print(";"); print(g0e1); print(")"))
|
D0Cstaload
(knd0,tknd,g0e1) =>
(print("D0Cstaload("); print(knd0); print(";"); print(tknd); print(";"); print(g0e1); print(")"))
//
|
D0Cdyninit(tknd,g0e1) =>
(
  (print("D0Cdyninit("); print(tknd); print(";"); print(g0e1); print(")")) )
(*
|
D0Cdynxgen(tknd,g0e1) =>
(
  prints("D0Cdynxgen(",tknd,";",g0e1,")") )
*)
//
(* ****** ****** *)
//
(*
HX-2024-07-20
Sat 20 Jul 2024 01:30:55 PM EDT
*)
|
D0Cextcode(tknd,g0e1) =>
(
  (print("D0Cextcode("); print(tknd); print(";"); print(g0e1); print(")")) )
//
(* ****** ****** *)
//
|
D0Cdatasort(tknd,dtcs) =>
(
  (print("D0Cdatasort("); print(tknd); print(";"); print(dtcs); print(")")) )
//
|
D0Cvaldclst(tknd,dcls) =>
(
  (print("D0Cvaldclst("); print(tknd); print(";"); print(dcls); print(")")) )
|
D0Cvardclst(tknd,dcls) =>
(
  (print("D0Cvardclst("); print(tknd); print(";"); print(dcls); print(")")) )
|
D0Cfundclst(tknd,t0qs,dcls) =>
(print("D0Cfundclst("); print(tknd); print(";"); print(t0qs); print(";"); print(dcls); print(")"))
//
|
D0Cexcptcon(tknd,tbar,tcns) =>
(print("D0Cexcptcon("); print(tknd); print(";"); print(tbar); print(";"); print(tcns); print(")"))
|
D0Cdatatype(tknd,dtps,wdcs) =>
(print("D0Cdatatype("); print(tknd); print(";"); print(dtps); print(";"); print(wdcs); print(")"))
//
|
D0Cdynconst(tknd,tqas,dcls) =>
(print("D0Cdynconst("); print(tknd); print(";"); print(tqas); print(";"); print(dcls); print(")"))
//
|
D0Cimplmnt0
(tknd,s0qs,t0qs,dqid,t0is,farg,sres,teq1,d0e2) =>
(
(print("D0Cimplmnt0("); print(tknd); print(";"));
(print(s0qs); print(";"); print(t0qs); print(";"); print(dqid); print(";"));
(print(t0is); print(";"); print(farg); print(";"); print(sres); print(";"); print(teq1); print(";"); print(d0e2); print(")")))
//
(*
HX-2025-04-19:
For if-guarded declarations
*)
|
D0Cifexp(tknd, gexp) =>
(
  (print("D0ifexp("); print(tknd); print(";"); print(gexp); print(")")))//#ifexp(gexp)
|
D0Celsif(tknd, gexp) =>
(
  (print("D0elsif("); print(tknd); print(";"); print(gexp); print(")")))//#elsif(gexp)
|
D0Cthen0(tknd) => (print("D0Cthen0("); print(tknd); print(")"))//#then0
|
D0Celse1(tknd) => (print("D0Celse1("); print(tknd); print(")"))//#else1
|
D0Cendif(tknd) => (print("D0Cendif("); print(tknd); print(")"))//#endif
//
|
D0Cerrck
(lvl(*err-level*),dcl) => (print("D0Cerrck("); print(lvl); print(";"); print(dcl); print(")"))
//
end (*let*) // end-of-[  d0ecl_fprint(  dcl  ,  out  )  ]

(* ****** ****** *)
//
#implfun
q0arg_fprint
( qag, out ) =
let
#impltmp
g_print$out<>() = out
in//in-of-let
case+
qag.node() of
| Q0ARGsome(id0,opt) =>
  (print("Q0ARGsome("); print(id0); print(";"); print(opt); print(")"))
end (*let*) // end of [q0arg_fprint(qag,out)]
//
#implfun
s0qag_fprint
( s0q, out ) =
let
#impltmp
g_print$out<>() = out
in//in-of-let
case+
s0q.node() of
|
S0QAGnone(tok) =>
(print("S0QAGnone("); print(tok); print(")"))
|
S0QAGsome(tkb,qas,tke) =>
(print("S0QAGsome("); print(tkb); print(";"); print(qas); print(";"); print(tke); print(")"))
end (*let*) // end of [s0qag_fprint(s0q,out)]
//
#implfun
t0qag_fprint
( t0q, out ) =
let
#impltmp
g_print$out<>() = out
in//in-of-let
case+
t0q.node() of
|
T0QAGnone(tok) =>
(print("T0QAGnone("); print(tok); print(")"))
|
T0QAGsome(tkb,qas,tke) =>
(print("T0QAGsome("); print(tkb); print(";"); print(qas); print(";"); print(tke); print(")"))
end (*let*) // end of [t0qag_fprint(t0q,out)]
//
(* ****** ****** *)
//
#implfun
t0iag_fprint
( t0i, out ) =
let
#impltmp
g_print$out<>() = out
in//in-of-let
case+
t0i.node() of
|
T0IAGnone(tok) =>
(print("T0IAGnone("); print(tok); print(")"))
|
T0IAGsome(tkb,ses,tke) =>
(print("T0IAGsome("); print(tkb); print(";"); print(ses); print(";"); print(tke); print(")"))
end (*let*) // end of [t0iag_fprint(t0i,out)]
//
(* ****** ****** *)
//
#implfun
a0typ_fprint
( a0t, out ) =
let
#impltmp
g_print$out<>() = out
in//in-of-let
//
case+
a0t.node() of
|
A0TYPsome(s0e1,topt) =>
(
  (print("A0TYPsome("); print(s0e1); print(";"); print(topt); print(")")))
end (*let*) // end of [a0typ_fprint(a0t,out)]
//
(* ****** ****** *)
//
#implfun
d0arg_fprint
( d0a, out ) =
let
#impltmp
g_print$out<>() = out
in//let
//
case+
d0a.node() of
|
D0ARGnone
(  tok0  ) =>
(print("D0ARGnone("); print(tok0); print(")"))
|
D0ARGsta0
(tbeg,sqas,tend) =>
(print("D0ARGsta0("); print(tbeg); print(";"); print(sqas); print(";"); print(tend); print(")"))
|
D0ARGdyn1
(  dpid  ) =>
(print("D0ARGdyn1("); print(dpid); print(")"))
|
D0ARGdyn2
(tbeg,a0ts,atsq,tend) =>
(print("D0ARGdyn2("); print(tbeg); print(";"); print(a0ts); print(";"); print(atsq); print(";"); print(tend); print(")"))
//
end (*let*) // end of [d0arg_fprint(d0a,out)]
//
(* ****** ****** *)

#implfun
g0edf_fprint
( gedf, out ) =
let
#impltmp
g_print$out<>() = out
in//let
//
case+ gedf of
|
G0EDFnone() =>
(print("G0EDFnone("); print(")"))
|
G0EDFsome(topt,g0e1) =>
(print("G0EDFsome("); print(topt); print(";"); print(g0e1); print(")"))
//
end (*let*) // end of [g0edf_fprint(gedf,out)]

(* ****** ****** *)

#implfun
d0edf_fprint
( dedf, out ) =
let
#impltmp
g_print$out<>() = out
in//let
//
case+ dedf of
|
D0EDFnone() =>
(print("D0EDFnone("); print(")"))
|
D0EDFsome(topt,d0e1) =>
(print("D0EDFsome("); print(topt); print(";"); print(d0e1); print(")"))
//
end (*let*) // end of [d0edf_fprint(dedf,out)]

(* ****** ****** *)

#implfun
a0tdf_fprint
( atdf, out ) =
let
#impltmp
g_print$out<>() = out
in//let
//
case+ atdf of
|
A0TDFsome() =>
(print("A0TDFsome("); print(")"))
|
A0TDFlteq(tok,s0e) =>
(print("A0TDFlteq("); print(tok); print(";"); print(s0e); print(")"))
|
A0TDFeqeq(tok,s0e) =>
(print("A0TDFeqeq("); print(tok); print(";"); print(s0e); print(")"))
//
end (*let*) // end of [a0tdf_fprint(atdf,out)]

(* ****** ****** *)
//
#implfun
precopt_fprint
 ( popt, out ) =
(
case+ popt of
|
PRECnil0() =>
print("PRECnil0()")
|
PRECint1(int) =>
(print("PRECint1("); print(int); print(")"))
|
PRECopr2(opr, pmd) =>
(print("PRECopr2("); print(opr); print(";"); print(pmd); print(")"))
) where
{
  #impltmp g_print$out<>() = out
} (*where*) // end of [precopt_fprint(...)]
//
#implfun
precint_fprint
 ( pint, out ) =
(
case+ pint of
|
PINTint1(int) =>
(print("PINTint1("); print(int); print(")"))
|
PINTopr2(opr, int) =>
(print("PINTopr2("); print(opr); print(";"); print(int); print(")"))
) where
{
  #impltmp g_print$out<>() = out
} (*where*) // end of [precint_fprint(...)]
//
#implfun
precmod_fprint
  (pmod, out) =
let
#impltmp
g_print$out<>() = out
in//let
case+ pmod of
|
PMODnone((*void*)) =>
(print("PRECMODnone("); print(")"))
|
PMODsome(tkb, int, tke) =>
(print("PMODsome("); print(tkb); print(";"); print(int); print(";"); print(tke); print(")"))
end (*let*) // end of [precmod_fprint(...)]
//
(* ****** ****** *)
//
#implfun
s0res_fprint
( sres, out ) =
let
#implfun
g_print$out<>() = out
in//let
case+ sres of
|
S0RESnone() =>
(print("S0RESnone("); print(")"))
|
S0RESsome(seff, s0e1) =>
(print("S0RESsome("); print(seff); print(";"); print(s0e1); print(")"))
end (*let*) // end of [s0res_fprint(...)]
//
#implfun
s0eff_fprint
( seff, out ) =
let
#implfun
g_print$out<>() = out
in//let
case+ seff of
|
S0EFFnone(tok0) =>
(print("S0EFFnone("); print(tok0); print(")"))
|
S0EFFsome(tbeg,s0fs,tend) =>
(print("S0EFFsome("); print(tbeg); print(";"); print(s0fs); print(";"); print(tend); print(")"))
end (*let*) // end of [s0eff_fprint(...)]
//
(* ****** ****** *)
//
#implfun
d0res_fprint
( dres, out ) =
let
#implfun
g_print$out<>() = out
in//let
case+ dres of
|
D0RESnone() =>
(print("D0RESnone("); print(")"))
|
D0RESsome(teq0, s0e1) =>
(print("D0RESsome("); print(teq0); print(";"); print(s0e1); print(")"))
end (*let*) // end of [d0res_fprint(...)]
//
(* ****** ****** *)

#implfun
d0valdcl_fprint
 ( dval, out ) = let
//
val dpat = dval.dpat()
val tdxp = dval.tdxp()
val wsxp = dval.wsxp()
//
#impltmp g_print$out<>() = out
//
in//let
(
(print("D0VALDCL("); print(dpat); print(";"); print(tdxp); print(","); print(wsxp); print(")")))
end(*let*)//end-of-[d0valdcl_fprint(dval,out)]

(* ****** ****** *)

#implfun
d0vardcl_fprint
 ( dvar, out ) = let
//
val dpid = dvar.dpid()
val vpid = dvar.vpid()
val sres = dvar.sres()
val dini = dvar.dini()
//
#impltmp g_print$out<>() = out
//
in//let
(
print("D0VARDCL(");
(print(dpid); print(";"); print(vpid); print(";"); print(sres); print(","); print(dini); print(")")))
end(*let*)//end-of-[d0vardcl_fprint(dvar,out)]

(* ****** ****** *)

#implfun
d0fundcl_fprint
 ( dfun, out ) = let
//
val dpid = dfun.dpid()
val farg = dfun.farg()
val sres = dfun.sres()
val tdxp = dfun.tdxp()
val wsxp = dfun.wsxp()
//
#impltmp g_print$out<>() = out
//
in//let
(
(print("D0FUNDCL("); print(dpid); print(";"));
(print(farg); print(";"); print(sres); print(";"); print(tdxp); print(","); print(wsxp); print(")")))
end(*let*)//end-of-[d0fundcl_fprint(dfun,out)]

(* ****** ****** *)

#implfun
d0cstdcl_fprint
 ( dcst, out ) =
let
//
(*
val lctn = dcst.lctn()
*)
val dpid = dcst.dpid()
val darg = dcst.darg()
val sres = dcst.sres()
val dres = dcst.dres()
//
#impltmp g_print$out<>() = out
//
in//let
(print("D0CSTDCL("); print(dpid); print(";"); print(darg); print(";"); print(sres); print(";"); print(dres); print(")"))
end (*let*) // end of [d0cstdcl_fprint]

(* ****** ****** *)

#implfun
d0parsed_fprint
 ( dpar, out ) = let
//
val
stadyn =
d0parsed_get_stadyn(dpar)
val
nerror =
d0parsed_get_nerror(dpar)
val
source =
d0parsed_get_source(dpar)
val
parsed =
d0parsed_get_parsed(dpar)
//
#impltmp g_print$out<>() = out
//
in//let
(
print("D0PARSED(");
(print(stadyn); print(";"); print(nerror); print(";"); print(source); print(";"); print(parsed); print(")")))
end(*let*)//end-of-[d0parsed_fprint(dpar,out)]

(* ****** ****** *)
//
#implfun
wd0eclseq_fprint
 ( wdcs , out ) =
let
#impltmp g_print$out<>() = out
in//let
case+ wdcs of
|
WD0CSnone() =>
(print("WD0CSnone("); print(")"))
|
WD0CSsome(tbeg, topt, dcls, tend) =>
(
(print("WD0CSsome("); print(tbeg); print(";"); print(topt); print(";"); print(dcls); print(";"); print(tend); print(")")))
end (*let*) // end of [ wd0eclseq_fprint(wdcs,out) ]
//
(* ****** ****** *)
//
#implfun
tkend_WHERE_fprint
  ( tend , out ) =
let
#impltmp g_print$out<>() = out
//
in//let
case+ tend of
|
tkend_WHERE_cons1(tok1) =>
(print("tkend_WHERE_cons1("); print(tok1); print(")"))
(*
|
tkend_WHERE_cons2(tok1,topt) =>
prints("tkend_WHERE_cons2(",tok1,";",topt,")")
*)
end (*let*) // end of [ tkend_WHERE_fprint(tend,out) ]
//
(* ****** ****** *)
//
#implfun
d0eclseq_WHERE_fprint
  ( wdcs , out ) =
let
#impltmp g_print$out<>() = out
//
in//let
case+ wdcs of
|
d0eclseq_WHERE
(tbeg, topt, dcls, tend) =>
(
(print("d0eclseq_WHERE("); print(tbeg); print(";"); print(topt); print(";"); print(dcls); print(";"); print(tend); print(")"))
)
end (*let*) // end of [ d0eclseq_WHERE_fprint(wdcs,out) ]
//
(* ****** ****** *)
(* ****** ****** *)
//
(***********************************************************************)
(* end of [ATS3/XATSOPT_srcgen2_DATS_dynexp0_print0.dats] *)
(***********************************************************************)
