////////////////////////////////////////////////////////////////////////.
//
// CATS/GO/lsp_floor.cats — the Go extern floor of the ATS3 LSP server.
// Spliced into the assembled package by tools/build.sh ($->_ mangled).
// Surface: stdio bytes + monotonic clock + (M6) the in-process check
// floor — setenv, a panic guard, and the runtime capture/buffer-FILR
// wrappers.  Types are belief-consistent with DATS/lsp_floor.dats:
// string <-> Go string, sint <-> int, void -> any.  The ATS side is
// single-threaded; the goroutines here only pump I/O into buffers.
//
// Needs `import ("os"; "time"; "xatsgo")`.
//
////////////////////////////////////////////////////////////////////////.
//
// ---- stdin: one pump goroutine feeds a channel; poll+read share it ----
var xats2goLspStdinCh chan []byte
var xats2goLspStdinPend []byte
var xats2goLspStdinEOF bool
//
func xats2goLspStdinEnsure() {
	if xats2goLspStdinCh != nil {
		return
	}
	ch := make(chan []byte, 64)
	xats2goLspStdinCh = ch
	go func() {
		for {
			buf := make([]byte, 65536)
			n, err := os.Stdin.Read(buf)
			if n > 0 {
				ch <- buf[:n]
			}
			if err != nil {
				close(ch)
				return
			}
		}
	}()
}
//
// BLOCKING read of some bytes from stdin; "" exactly at EOF.
func XATS2GO_LSP_read_chunk() string {
	xats2goLspStdinEnsure()
	if len(xats2goLspStdinPend) > 0 {
		s := string(xats2goLspStdinPend)
		xats2goLspStdinPend = nil
		return s
	}
	if xats2goLspStdinEOF {
		return ""
	}
	b, ok := <-xats2goLspStdinCh
	if !ok {
		xats2goLspStdinEOF = true
		return ""
	}
	return string(b)
}
//
// wait up to ms (ms < 0 = forever) for input: 1 data, 0 timeout, 2 EOF.
func XATS2GO_LSP_poll_stdin(ms int) int {
	xats2goLspStdinEnsure()
	if len(xats2goLspStdinPend) > 0 {
		return 1
	}
	if xats2goLspStdinEOF {
		return 2
	}
	if ms < 0 {
		b, ok := <-xats2goLspStdinCh
		if !ok {
			xats2goLspStdinEOF = true
			return 2
		}
		xats2goLspStdinPend = b
		return 1
	}
	t := time.NewTimer(time.Duration(ms) * time.Millisecond)
	defer t.Stop()
	select {
	case b, ok := <-xats2goLspStdinCh:
		if !ok {
			xats2goLspStdinEOF = true
			return 2
		}
		xats2goLspStdinPend = b
		return 1
	case <-t.C:
		return 0
	}
}
//
func XATS2GO_LSP_write_out(s string) any {
	os.Stdout.WriteString(s)
	return nil
}
//
func XATS2GO_LSP_write_log(s string) any {
	os.Stderr.WriteString(s)
	return nil
}
//
var xats2goLspEpoch = time.Now()
//
func XATS2GO_LSP_now_ms() int {
	return int(time.Since(xats2goLspEpoch).Milliseconds())
}
//
// ---- M6: the IN-PROCESS check floor -----------------------------------
// The compiler is linked into this binary (wire-server.sh); checks run
// in-process via tchk_check (UTIL/xats2go_tchecklib).  The old
// spawn/reap process floor is gone with it.
//
// set an environment variable (XATSHOME before the prelude loads; the
// compiler reads it via its getenv leaf).
func XATS2GO_LSP_setenv(name string, value string) any {
	os.Setenv(name, value)
	return nil
}
//
// run the closure with a panic guard: 1 = completed, 0 = recovered.
// A frontend abort (the compiler's exit-worthy errors surface as
// panics in the GO arm) fails ONE check, never the server.  Closure
// convention per CATS/GO/strn000.cats: `(sint)->void` emits as
// `func(int) any`.
func XATS2GO_LSP_guard(f0 func(int) any) int {
	ok := 1
	func() {
		defer func() {
			if r := recover(); r != nil {
				os.Stderr.WriteString("ats3-lsp: check aborted (recovered panic)\n")
				ok = 0
			}
		}()
		f0(0)
	}()
	return ok
}
//
// the check's results cross the prelude fence via the runtime stash:
// the compiler-world glue deposits the captured report + index texts,
// the server collects them here after the (guarded) check returns.
// (The tchk entry-point shims XATS2GO_LSP_tchk_prelude_load/tchk_check
// are GENERATED by wire-server.sh — they forward to the glue module's
// stamped Z_ symbols.)
func XATS2GO_LSP_take_rep() string { return xatsgo.Xats_XATS2GO_lsp_take_rep() }
//
func XATS2GO_LSP_take_idx() string { return xatsgo.Xats_XATS2GO_lsp_take_idx() }
//
// terminate the server process (LSP: exit 0 after shutdown, 1 without).
func XATS2GO_LSP_exit(code int) any {
	os.Exit(code)
	return nil
}
//
////////////////////////////////////////////////////////////////////////.
// end of [lsp_floor.cats]
////////////////////////////////////////////////////////////////////////.
